blog/urls.py
from django.urls.conf import path
from blog import views


app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list')
]

instagram/urls.py
from django.urls import path, register_converter
from instagram import views
from instagram.converters import DayConverter, MonthConverter, YearConverter


register_converter(YearConverter, 'year')
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')
app_name = 'instagram'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit', views.post_edit, name='post_edit'),
    path('<int:pk>/delete', views.post_delete, name='post_delete'),
    # re_path(r'(?P<pk>\d+)/$', views.post_detail,)
    # path('archives/2020/', views.archives_year),
    # path('archives/2019/', views.archives_year)
    # path('archives/<int:year>/', views.archives_year)
    # re_path('archives/(?P<year>\\d+)/', views.archives_year)
    # re_path(r'archives/(?P<year>20\d{2})/', views.archives_year)
    # path('archives/<year:year>/', views.archives_year)
    path('archive/', views.post_arcive, name='post_arcive'),
    path('archive/<year:year>/', views.post_arcive__year, name="post_arcive__year"),
    path('new/', views.post_new, name='post_new')

]

youm_test/urls.py
from typing import Union
from django.conf import settings
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin
from django.urls import URLPattern, URLResolver, path
from django.urls.conf import include
from django.conf.urls.static import static
import debug_toolbar


# class RootView(TemplateView):
#     template_name = 'root.html'

class RootView(RedirectView):
    pattern_name = 'instagram:post_list'


urlpatterns: list[Union[URLPattern, URLResolver]] = [
    path('admin/', admin.site.urls),

    # path('', TemplateView.as_view(template_name='root.html'), name='root'),
    # path('', RootView.as_view(), name='root'),
    # path('', RedirectView.as_view(
    #     # url='/instagram/'
    #     pattern_name='instagram:post_list'
    # ), name='root'),
    path('', RootView.as_view(), name='root'),
    path('blog/', include('blog.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]

instagram/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(validators=[MinLengthValidator(10)])
    is_public = models.BooleanField(default=False, verbose_name='공개')
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag_set = models.ManyToManyField('Tag', blank=True)

    def get_absolute_url(self):
        return reverse("instagram:post_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        # return f"Post object({self.pk})"
        return self.message

    class Meta:
        ordering = ['-id']
    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메세지 글자수"


class Comment(models.Model):
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, limit_choices_to={'is_public': True})
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # post_set = models.ManyToManyField('Post', blank=True)

    def __str__(self) -> str:
        return self.name

instagram/forms.py
import re
from django import forms
from instagram.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'message', 'photo', 'tag_set', 'is_public'
        ]

    def clean_message(self):
        data = self.cleaned_data.get('message')
        if data:
            data = re.sub(r'[a-zA-Z]+', '', data)
        return data

instagram/views.py
from typing import Any, Union
from django.forms import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
# from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.urls import reverse_lazy
# from django.utils.decorators import method_decorator
# from django.shortcuts import get_object_or_404, render
# from django.contrib.auth.decorators import login_required
from django.views.generic import (
    CreateView, ListView, YearArchiveView, ArchiveIndexView, DetailView, UpdateView, DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import query
from django.contrib import messages
from instagram.models import Post
from instagram.forms import PostForm


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('instagram:post_list')
    object: Union[Post, None] = None

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        response = super().get(request, *args, **kwargs)
        if self.object.author != request.user:
            messages.error(request, 'only author cna delete')
            return redirect(self.object)
        return response


post_delete = PostDeleteView.as_view()

# @login_required
# def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
#     post = get_object_or_404(Post, pk=pk)
#     if post.author != request.user:
#         messages.error(request, 'only author cna delete')
#         return redirect(post)
#     if request.method == 'POST':
#         post.delete()
#         messages.success(request, 'post deleted')
#         return redirect('instagram:post_list')
#     return render(request, 'instagram/post_delete.html', {
#         'post': post
#     })


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    object: Union[Post, None] = None

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        response = super().get(request, *args, **kwargs)
        if self.object.author != request.user:
            messages.error(request, 'only author cna edit')
            return redirect(self.object)
        return response

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        messages.success(self.request, 'post edited')
        return super().form_valid(form)


post_edit = PostUpdateView.as_view()
# @login_required
# def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
#     post = get_object_or_404(Post, pk=pk)

#     if post.author != request.user:
#         messages.error(request, 'only author cna edit')
#         return redirect(post)

#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save()
#             messages.success(request, 'post edited')
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': post
#     })


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        messages.success(self.request, 'post saved')
        return super().form_valid(form)


post_new = PostCreateView.as_view()
# @login_required
# def post_new(request: HttpRequest):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             messages.success(request, 'post saved')
#             return redirect(post)
#     else:
#         form = PostForm()
#     return render(request, 'instagram/post_form.html', {
#         'form': form
#     })

# @method_decorator(login_required, name='dispatch')


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10

    # @method_decorator(login_required)
    # def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
    #     return super().dispatch(request, *args, **kwargs)


# post_list = login_required(PostListView.as_view())
post_list = PostListView.as_view()

# post_list = ListView.as_view(model=Post)


# @login_required
# def post_list(request: HttpRequest) -> HttpResponse:
#     q = request.GET.get('q', '')
#     qs = Post.objects.all()
#     if q:
#         qs = qs.filter(message__icontains=q)

#     messages.info(request, 'test!!!!!')
#     return render(request, 'instagram/post_list.html', {
#         'post_list': qs,
#         'q': q
#     })


# @method_decorator(login_required, name='dispatch')
class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    # queryset = Post.objects.filter(is_public=True)
    # pass

    def get_queryset(self) -> query.QuerySet:
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)
        return qs


post_detail = PostDetailView.as_view()

# post_detail = DetailView.as_view(
#     model=Post, queryset=Post.objects.filter(is_public=True))
# def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     post = get_object_or_404(Post, pk=pk)
#     return render(request, 'instagram/post_detail.html', {
#         'post': post
#     })
#     # try:
#     #     post = Post.objects.get(pk=pk)
#     # except Post.DoesNotExist as err:
#     #     raise Http404 from err
#     # return render(request, 'instagram/post_detail.html', {
#     #     'post': post
#     # })
#     # response = HttpResponse()
#     # response.write(f'{pk}')
#     # return response


class PostArchiveIndexView(ArchiveIndexView):
    model = Post
    date_field = 'created_at'
    paginate_by = 10


post_arcive = PostArchiveIndexView.as_view()
# def archives_year(request: HttpRequest, year: int) -> HttpResponse:
#     return HttpResponse(f'{year}')
#     # return HttpResponse(f'2020')


class PostYearArchiveView(YearArchiveView):
    model = Post
    date_field = 'created_at'
    make_object_list = True


post_arcive__year = PostYearArchiveView.as_view()

instagram/templates/instagram/post_archive.html
<ul>
  {% for post in latest %}
  <li>{{ post.pk }} {{ post.created_at }}: {{ post.message }}</li>
  {% endfor %}
</ul>
<ul>
  {% for date in date_list %}
  <li>{{ date|date:'Y' }}</li>
  {% endfor %}
</ul>

instagram/templates/instagram/post_archive_year.html
<ul>
  {% for date in date_list %}
  <li>{{ date|date }}</li>
  {% endfor %}
</ul>

<div>
  <h1>All Articles for {{ year|date:"Y" }}</h1>
  {% for obj in object_list %}
  <p>{{ obj.message }} - {{ obj.created_at|date:"F j, Y" }}</p>
  {% endfor %}
</div>
{{previous_year}} {{year}} {{next_year}}

instagram/templates/instagram/post_confirm_delete.html
{% extends 'instagram/layout.html' %} 
{% load bootstrap5 %} 
{% block title %}
post delete {{post.pk}}
{%endblock title %} 
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <div class="alert alert-danger">really??</div>
  <a href="{{post.get_absolute_url}}" class="btn btn-secondary">back</a>
  <input type="submit" value="delete?" class="btn btn-danger" />
</form>
{% endblock content %}

instagram/templates/instagram/post_delete.html
{% extends 'instagram/layout.html' %} 
{% load bootstrap5 %} 
{% block title %}
post delete {{post.pk}}
{%endblock title %} 
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <div class="alert alert-danger">really??</div>
  <a href="{{post.get_absolute_url}}" class="btn btn-secondary">back</a>
  <input type="submit" value="delete?" class="btn btn-danger" />
</form>
{% endblock content %}

instagram/templates/instagram/post_detail.html
{% extends 'instagram/layout.html' %}
{% block title %}
post detali {{post.pk}}
{%endblock title %}
{% block content %}
<h2>author:{{post.author}}</h2>
{% if post.photo %}
<div>
  <img style="width: 100px" src="{{post.photo.url}}" alt="{{post.photo}}" />
</div>
{% endif %} 
{{post.message|linebreaks}}
<hr />
<a href="{% url 'instagram:post_list' %}" class="btn btn-primary">list</a>
<a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">edit</a>
<a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">delete</a>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %} 
{% load bootstrap5 %}
{% block title %} post new {{post.pk}}
{%endblock title %} {% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  <table>
    {% csrf_token %} 
    {% bootstrap_form form %}
  </table>
  <input type="submit" value="save" class="btn btn-primary"/>
</form>
<hr />
{% if post %}
<a href="{{post.get_absolute_url}}" class="btn btn-secondary">info</a>
{% endif %}
<a href="{% url 'instagram:post_list' %}" class="btn btn-primary">list</a>
{% endblock content %}

instagram/templates/instagram/post_list.html
{% extends 'instagram/layout.html' %} 
{% load bootstrap5 %} 
{% block title%}
post list
{% endblock title %} 
{% block content %}
<form action="" method="GET">
  <input type="text" name="q" value="{{q}}" />
  <input type="submit" value="search" />
</form>
<div class="d-grid gap-2">
  <a
    href="{% url 'instagram:post_new' %}"
    class="btn btn-primary btn-block mt-3 mb-3"
    >새 포스팅</a
  >
</div>
<table class="table table-bordered table-hover">
  {% for post in post_list %}
  <tr>
    <td>{{post.pk}}</td>
    <td>
      <a
        href="
              {% comment %} {% url 'instagram:post_detail' post.pk %} {% endcomment %}
              {{post.get_absolute_url}}
            "
      >
        {{post.message}}
      </a>
    </td>
    <td>
      {% if post.photo%}
      <img src="{{post.photo.url}}" alt="{{post.photo}}" style="width: 100px" />
      {% else %} 
      no photo 
      {% endif %}
    </td>
  </tr>
  {% endfor %}
</table>
{{is_paginated}} {{page_obj}} 
{% if is_paginated %} 
{% bootstrap_pagination page_obj size='small' justify_content='center' %} 
{% endif %} 
{% endblock content %}